Provide integration tests for the key functionalities #13
eclipse-kanto/system-metrics pull request #21
Opened 2022-11-23 13:59 UTC by hristobojilov

[#13] Provide integration tests for the key functionalities 

Signed-off-by: Hristo Bozhilov <Hristo.Bozhilov@bosch.io>

2022-11-24 09:02 UTC, e-grigorov requested changes

2022-11-24 11:21 UTC, hristobojilov commented on integration/metrics_test.go
> +		"frequency": "10 seconds",
The tc name is enough descriptive.

2022-11-24 11:25 UTC, hristobojilov commented on integration/metrics_test.go
> +		if strings.Index(msg.Path, "/outbox/") == -1 {
It's not possible to filter by RQL expressions

2022-11-24 11:35 UTC, hristobojilov commented on integration/metrics_test.go
> +	err := suite.doTestMetrics(map[string]interface{}{
This is one test scenario with jira just with different parameters.

2022-11-24 11:44 UTC, hristobojilov commented on integration/metrics_test.go
> +			return false, nil
This it to ignore the error and continue with the next message.

2022-11-24 11:45 UTC, hristobojilov commented on integration/metrics_test.go
> +			return false, nil
This it to ignore the error and continue with the next message.

2022-11-24 11:45 UTC, e-grigorov commented on integration/metrics_test.go
> +		"frequency": "10 seconds",
I'll try to explain with an example: 10 seconds. The question is what's wrong with this unit? It's called `seconds`. The comment will help the new readers.

2022-11-24 11:47 UTC, e-grigorov commented on integration/metrics_test.go
> +		if strings.Index(msg.Path, "/outbox/") == -1 {
What do you mean? For example, container management TC does similar filtering.

2022-11-24 11:53 UTC, e-grigorov commented on integration/metrics_test.go
> +	err := suite.doTestMetrics(map[string]interface{}{
My comment was just a preference but there is no issue to keep the current approach. Actually, it's known as: https://github.com/golang/go/wiki/TableDrivenTests but then TC should have more informative error messages i.e. on fail, the code should not be checked.

2022-11-24 11:54 UTC, e-grigorov commented on integration/metrics_test.go
> +			return false, nil
It's clear, the question was more whether it's an expected to have an error here or not.

2022-11-24 11:55 UTC, e-grigorov commented on integration/metrics_test.go
> +			return false, nil
Does the TC expect such errors?

2022-11-25 10:28 UTC, e-grigorov commented on integration/metrics_test.go
> +		if strings.Index(msg.Path, "/outbox/") == -1 {
Ditto doesn't support this i.e. the filter cannot be used for this type.

2022-11-25 10:31 UTC, e-grigorov commented on NOTICE.md
> +github.com/stretchr/testify (1.8.1)
For the binary components, the notice contains only the libraries that will be included in the binary artifact. The test libraries should not be there.

2022-11-25 10:57 UTC, e-grigorov requested changes

2022-11-25 10:57 UTC, e-grigorov commented on integration/metrics_test.go
> +	dataAction       = "data"
There are pathData, topicData, I guess that this one should be: actionData.

2022-11-25 10:57 UTC, e-grigorov commented on integration/metrics_test.go
> +
If the originator is not found after this loop, TC has to fail. originatorFound can be removed then.

2022-11-25 10:57 UTC, e-grigorov commented on integration/metrics_test.go
> +				return false, fmt.Errorf("Invalid metrics ID: %s", mm.ID)
Do we need to stop the event processing here?

2022-11-25 10:57 UTC, e-grigorov commented on integration/metrics_test.go
> +	_, err = util.ExecuteOperation(suite.Cfg, suite.metricsFeatureURL, "request", params)
Current time can be collected before the request, then the metrics timestamp can be validated also.

2022-11-25 10:57 UTC, e-grigorov commented on integration/metrics_test.go
> +func (suite *systemMetricsSuite) testMetrics(params map[string]interface{}, originators ...string) error {
I would suggest to rename `originators` to `expectedOriginators`.

2022-11-25 10:57 UTC, e-grigorov commented on integration/metrics_test.go
> +	assert.NoError(suite.T(), err, "metrics event from at least one originator system/suite-connector should be received")
I would suggest to improve the validation and instead of `at least one` to expect all of them.

2022-11-25 10:57 UTC, e-grigorov commented on integration/metrics_test.go
> +	assert.NoError(suite.T(), err, "metrics event should be received")
Adjust the error message as it was implemented for all other test methods.

2022-11-25 10:57 UTC, e-grigorov commented on integration/metrics_test.go
> +	assert.Error(suite.T(), err, "metrics events for test.process should not be received")
Unify the wording, it should be `metrics event` or `metrics events`, not both of them.

2022-11-25 10:57 UTC, e-grigorov commented on integration/metrics_test.go
> +		_, err := util.ExecuteOperation(suite.Cfg, suite.metricsFeatureURL, "request", map[string]interface{}{
This seems to be a duplicated code.

2022-11-25 14:31 UTC, e-grigorov approved these changes

2022-11-25 14:38 UTC, merged