Ensure no response is sent to messages that don't require a response
eclipse-kanto/system-metrics pull request #24
Opened 2023-01-03 08:32 UTC by gabriela-yoncheva

[#20] Ensure no response is sent to messages that don't require a response
Problem found:
- Sending a response to a command was not determined by correlation_id and not the response-required header.

Fixes applied:
- Ensured no reply is sent to messages that don't require a response, by checking the response-required header.

Signed-off-by: Gabriela Yoncheva <Gabriela.Yoncheva@bosch.io>

2023-01-04 09:30 UTC, antoniyatrifonova approved these changes

2023-01-04 11:47 UTC, hristobojilov approved these changes

2023-01-05 09:11 UTC, dimitar-dimitrow commented on internal/metrics/feature_test.go
> +			protocol.WithCorrelationID("request_invalid_duration")))
Maybe it is a good idea to also add a test that checks that no response is received when response required is not set.

2023-01-10 09:29 UTC, dimitar-dimitrow requested changes

2023-01-10 09:29 UTC, dimitar-dimitrow commented on internal/metrics/feature_test.go
> +	assertDefaultMetricData(t, mc)
The metrics reporting should be stopped at the end of the test, the provider should be stopped and ditto client disconnected. The same as TestHandleRequestPublishedMessages, but with no response required header.

2023-01-10 10:26 UTC, antoniyatrifonova approved these changes

2023-01-10 11:38 UTC, dimitar-dimitrow approved these changes

2023-01-10 11:43 UTC, merged